#!/usr/bin/env bun
/**
 * Asset metadata + library documentation generator.
 *
 * Walks img/ and emits two tracked, publicly-served artifacts:
 *   img/manifest.json  — machine-readable metadata (path, type, size, dimensions, hash, url)
 *   CATALOG.md         — human-readable catalog with inline previews
 *
 * The content hash is the first 12 hex chars of the file's sha256 — a stable, per-file
 * fingerprint usable for cache-busting/versioning by consumers.
 *
 * Usage:
 *   bun tools/manifest.ts          # (re)generate both files
 *   bun tools/manifest.ts --check  # CI mode: exit 1 if either file is stale
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, extname } from 'node:path';
import { createHash } from 'node:crypto';
import sharp from 'sharp';

const IMG_DIR = 'img';
const MANIFEST_PATH = join(IMG_DIR, 'manifest.json');
const CATALOG_PATH = 'CATALOG.md';
const PAGES_BASE = 'https://marquelmedia.github.io/assets';
const MEDIA = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg']);

type Asset = {
  path: string; // posix, repo-relative (e.g. img/logo.svg)
  type: string; // extension without the dot
  bytes: number;
  width: number | null;
  height: number | null;
  frames?: number; // animated raster only
  hash: string; // sha256, first 12 hex chars
  url: string; // public GitHub Pages URL
  variants?: string[]; // alternate-format siblings (e.g. img/logo.webp)
  variantOf?: string; // set on a variant, points back to its source
};

async function* walk(dir: string): AsyncGenerator<string> {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (entry.name.startsWith('.')) continue; // skip .DS_Store, dotfiles
    const full = join(dir, entry.name);
    if (entry.isDirectory()) yield* walk(full);
    else yield full;
  }
}

function svgDimensions(svg: string): { width: number | null; height: number | null } {
  const num = (v?: string) => {
    if (!v) return null;
    const n = parseFloat(v);
    return Number.isFinite(n) ? Math.round(n) : null;
  };
  const w = num(svg.match(/\bwidth="([\d.]+)/)?.[1]);
  const h = num(svg.match(/\bheight="([\d.]+)/)?.[1]);
  if (w && h) return { width: w, height: h };
  // Fall back to the intrinsic viewBox size (min-x min-y width height).
  const vb = svg.match(/viewBox="\s*[-\d.]+\s+[-\d.]+\s+([\d.]+)\s+([\d.]+)/);
  if (vb) return { width: num(vb[1]), height: num(vb[2]) };
  return { width: w, height: h };
}

async function describe(file: string): Promise<Asset> {
  const buf = await readFile(file);
  const ext = extname(file).toLowerCase();
  const posix = file.split(/[\\/]/).join('/');
  const base: Asset = {
    path: posix,
    type: ext.slice(1),
    bytes: buf.length,
    width: null,
    height: null,
    hash: createHash('sha256').update(buf).digest('hex').slice(0, 12),
    url: `${PAGES_BASE}/${posix}`,
  };

  if (ext === '.svg') {
    return { ...base, ...svgDimensions(buf.toString('utf8')) };
  }
  try {
    const meta = await sharp(buf, { animated: ext === '.gif' }).metadata();
    base.width = meta.width ?? null;
    // sharp reports total height across frames for animated inputs
    base.height = meta.pageHeight ?? meta.height ?? null;
    if (meta.pages && meta.pages > 1) base.frames = meta.pages;
  } catch {
    // leave dimensions null if the file can't be probed
  }
  return base;
}

/** Link generated alternate-format siblings (e.g. logo.webp) back to their source. */
function linkVariants(assets: Asset[]): void {
  const VARIANT_TYPES = new Set(['webp', 'avif']);
  const stem = (p: string) => p.slice(0, -extname(p).length);
  for (const asset of assets) {
    if (!VARIANT_TYPES.has(asset.type)) continue;
    const source = assets.find(
      (a) => a !== asset && !VARIANT_TYPES.has(a.type) && stem(a.path) === stem(asset.path),
    );
    if (!source) continue;
    asset.variantOf = source.path;
    (source.variants ??= []).push(asset.path);
  }
}

function renderCatalog(assets: Asset[]): string {
  const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;
  const dims = (a: Asset) =>
    a.width && a.height
      ? `${a.width}×${a.height}${a.frames ? ` · ${a.frames}f` : ''}`
      : '—';

  const rows = assets
    .map(
      (a) =>
        `| ![${a.path}](${a.path}) | \`${a.path}\` | ${a.type} | ${dims(a)} | ${kb(
          a.bytes,
        )} | \`${a.hash}\` |`,
    )
    .join('\n');

  return `# Asset Catalog

> Generated by \`bun run manifest\` — do not edit by hand.
> Machine-readable metadata lives in [\`img/manifest.json\`](./img/manifest.json)
> (also served at \`${PAGES_BASE}/img/manifest.json\`).

${assets.length} shared assets. Previews use repo-relative paths and render on GitHub.

| Preview | Path | Type | Dimensions | Size | Hash |
|---|---|---|---|---|---|
${rows}
`;
}

async function main() {
  const check = process.argv.includes('--check');

  const files: string[] = [];
  for await (const f of walk(IMG_DIR)) {
    if (MEDIA.has(extname(f).toLowerCase())) files.push(f);
  }
  files.sort();

  const assets: Asset[] = [];
  for (const f of files) assets.push(await describe(f));

  linkVariants(assets);

  const manifest = JSON.stringify({ assets }, null, 2) + '\n';
  const catalog = renderCatalog(assets);

  if (check) {
    const stale: string[] = [];
    for (const [path, next] of [
      [MANIFEST_PATH, manifest],
      [CATALOG_PATH, catalog],
    ] as const) {
      let current = '';
      try {
        current = await readFile(path, 'utf8');
      } catch {
        /* missing counts as stale */
      }
      if (current !== next) stale.push(path);
    }
    if (stale.length) {
      console.error(`Stale metadata: ${stale.join(', ')}`);
      console.error("Run 'bun run manifest' and commit the result.");
      process.exit(1);
    }
    console.log('Asset metadata up to date.');
    return;
  }

  await writeFile(MANIFEST_PATH, manifest);
  await writeFile(CATALOG_PATH, catalog);
  console.log(`Wrote ${MANIFEST_PATH} and ${CATALOG_PATH} (${assets.length} assets).`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
